onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/clk_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/rst_ni}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/operands_a_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/operands_b_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/operand_c_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/operand_d_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/is_boxed_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/rnd_mode_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/op_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/op_mod_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/src_fmt_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/dst_fmt_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/tag_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mask_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/aux_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/in_valid_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/in_ready_o}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/flush_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/result_o}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/status_o}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/extension_bit_o}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/tag_o}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mask_o}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/aux_o}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/out_valid_o}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/out_ready_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/busy_o}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/operands_a_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/operands_b_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/operand_c_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/operand_d_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/src_fmt_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/dst_fmt_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/inp_pipe_operands_a_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/inp_pipe_operands_b_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/inp_pipe_operand_c_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/inp_pipe_operand_d_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/inp_pipe_is_boxed_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/inp_pipe_rnd_mode_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/inp_pipe_op_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/inp_pipe_op_mod_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/inp_pipe_src_fmt_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/inp_pipe_dst_fmt_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/inp_pipe_tag_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/inp_pipe_mask_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/inp_pipe_aux_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/inp_pipe_valid_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/inp_pipe_ready}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/operands_post_inp_pipe}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/fmt_sign}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/fmt_exponent}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/fmt_mantissa}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/info_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/fmt_dst_sign}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/fmt_dst_exponent}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/fmt_dst_mantissa}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/operands_a}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/operands_b}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/operand_c}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/operand_d}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/info_a}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/info_b}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/info_c}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/info_d}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/any_operand_inf}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/any_operand_nan}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/signalling_nan}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/any_produced_nan}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/any_pos_inf}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/any_neg_inf}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/operand_inf_conditions}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/operand_nan_conditions}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/signalling_nan_conditions}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/nan_conditions}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/pos_inf_conditions}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/neg_inf_conditions}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/special_result}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/special_status}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/result_is_special}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/fmt_special_result}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/fmt_special_status}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/fmt_result_is_special}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mantissa_a}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mantissa_b}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/product}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/product_signed}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/exponent_product}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/shifted_product}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/shift_amount}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/sum_product}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/sum_product_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/operand_c_q2}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/operand_d_q2}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/info_d_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/dst_fmt_q2}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/rnd_mode_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/result_is_special_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/special_result_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/special_status_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mid_pipe_sum_product_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mid_pipe_operand_c_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mid_pipe_operand_d_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mid_pipe_info_d_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mid_pipe_dst_fmt_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mid_pipe_rnd_mode_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mid_pipe_res_is_spec_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mid_pipe_spec_res_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mid_pipe_spec_stat_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mid_pipe_tag_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mid_pipe_mask_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mid_pipe_aux_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mid_pipe_valid_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mid_pipe_ready}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/result_is_accumulator}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/accumulator_is_right_shifted}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/accumulator_shift_amount}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/accumulator_right_shift_amount}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/exponent_d}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/mantissa_d}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/signed_mantissa_d}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/accumulator_remaining}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/accumulator_shifted}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/sum_product_accumulator}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/accumulator_sticky}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/sum_product_accumulator_extended}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/sum_magnitude}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/sum_shifted}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/leading_zero_count}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/leading_zero_count_sgn}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/lzc_zeroes}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/final_tentative_exponent}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/norm_shamt}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/normalized_exponent}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/final_sign}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/final_mantissa}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/sum_sticky_bits}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/sticky_after_norm}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/final_exponent}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/pre_round_sign}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/pre_round_abs}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/round_sticky_bits}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/of_before_round}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/of_after_round}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/uf_before_round}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/uf_after_round}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/fmt_pre_round_abs}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/fmt_round_sticky_bits}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/fmt_of_after_round}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/fmt_uf_after_round}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/rounded_sign}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/rounded_abs}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/result_zero}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/fmt_result}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/regular_result}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/regular_status}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/result_d}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/status_d}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/out_pipe_result_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/out_pipe_status_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/out_pipe_tag_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/out_pipe_mask_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/out_pipe_aux_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/out_pipe_valid_q}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/gen_merged_slice/i_multifmt_slice/gen_num_lanes[0]/active_lane/lane_instance/dut/i_fpnew_sdotp_multi/out_pipe_ready}
add wave -noupdate /tb_fpnew/dut/clk_i
add wave -noupdate /tb_fpnew/dut/rst_ni
add wave -noupdate /tb_fpnew/dut/hart_id_i
add wave -noupdate /tb_fpnew/dut/operands_i
add wave -noupdate /tb_fpnew/dut/rnd_mode_i
add wave -noupdate /tb_fpnew/dut/op_i
add wave -noupdate /tb_fpnew/dut/op_mod_i
add wave -noupdate /tb_fpnew/dut/src_fmt_i
add wave -noupdate /tb_fpnew/dut/dst_fmt_i
add wave -noupdate /tb_fpnew/dut/int_fmt_i
add wave -noupdate /tb_fpnew/dut/vectorial_op_i
add wave -noupdate /tb_fpnew/dut/tag_i
add wave -noupdate /tb_fpnew/dut/simd_mask_i
add wave -noupdate /tb_fpnew/dut/in_valid_i
add wave -noupdate /tb_fpnew/dut/in_ready_o
add wave -noupdate /tb_fpnew/dut/flush_i
add wave -noupdate /tb_fpnew/dut/result_o
add wave -noupdate /tb_fpnew/dut/status_o
add wave -noupdate /tb_fpnew/dut/tag_o
add wave -noupdate /tb_fpnew/dut/out_valid_o
add wave -noupdate /tb_fpnew/dut/out_ready_i
add wave -noupdate /tb_fpnew/dut/busy_o
add wave -noupdate /tb_fpnew/dut/opgrp_in_ready
add wave -noupdate /tb_fpnew/dut/opgrp_out_valid
add wave -noupdate /tb_fpnew/dut/opgrp_out_ready
add wave -noupdate /tb_fpnew/dut/opgrp_ext
add wave -noupdate /tb_fpnew/dut/opgrp_busy
add wave -noupdate /tb_fpnew/dut/opgrp_outputs
add wave -noupdate /tb_fpnew/dut/is_boxed
add wave -noupdate /tb_fpnew/dut/simd_mask
add wave -noupdate /tb_fpnew/dut/arbiter_output
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/in_valid_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[2]/i_opgroup_block/in_valid_i}
add wave -noupdate -expand -label {Contributors: sim:/tb_fpnew/dut/gen_operation_groups[2]/i_opgroup_block/in_valid_i} -group {Contributors: {sim:/tb_fpnew/dut/gen_operation_groups[2]/i_opgroup_block/in_valid_i}} /tb_fpnew/dut/in_valid_i
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/clk_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/rst_ni}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/hart_id_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/operands_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/is_boxed_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/rnd_mode_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/op_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/op_mod_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/src_fmt_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/dst_fmt_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/int_fmt_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/vectorial_op_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/tag_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/simd_mask_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/in_valid_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/in_ready_o}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/flush_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/result_o}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/status_o}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/extension_bit_o}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/tag_o}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/out_valid_o}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/out_ready_i}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/busy_o}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/fmt_in_ready}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/fmt_out_valid}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/fmt_out_ready}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/fmt_busy}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/fmt_outputs}
add wave -noupdate {/tb_fpnew/dut/gen_operation_groups[5]/i_opgroup_block/arbiter_output}
add wave -noupdate /tb_fpnew/SRC_FMT
add wave -noupdate /tb_fpnew/clk_i
add wave -noupdate /tb_fpnew/rst_ni
add wave -noupdate /tb_fpnew/operands_i
add wave -noupdate /tb_fpnew/operands_a_i
add wave -noupdate /tb_fpnew/operands_b_i
add wave -noupdate /tb_fpnew/operand_c_i
add wave -noupdate /tb_fpnew/operand_d_i
add wave -noupdate /tb_fpnew/is_boxed_i
add wave -noupdate /tb_fpnew/rnd_mode_i
add wave -noupdate /tb_fpnew/op_i
add wave -noupdate /tb_fpnew/op_mod_i
add wave -noupdate /tb_fpnew/src_fmt_i
add wave -noupdate /tb_fpnew/dst_fmt_i
add wave -noupdate /tb_fpnew/int_fmt_i
add wave -noupdate /tb_fpnew/tag_i
add wave -noupdate /tb_fpnew/mask_i
add wave -noupdate /tb_fpnew/aux_i
add wave -noupdate /tb_fpnew/in_valid_i
add wave -noupdate /tb_fpnew/flush_i
add wave -noupdate /tb_fpnew/out_ready_i
add wave -noupdate /tb_fpnew/result_o
add wave -noupdate /tb_fpnew/status_o
add wave -noupdate /tb_fpnew/extension_bit_o
add wave -noupdate /tb_fpnew/tag_o
add wave -noupdate /tb_fpnew/mask_o
add wave -noupdate /tb_fpnew/aux_o
add wave -noupdate /tb_fpnew/in_ready_o
add wave -noupdate /tb_fpnew/out_valid_o
add wave -noupdate /tb_fpnew/busy_o
add wave -noupdate /tb_fpnew/file
add wave -noupdate /tb_fpnew/r
add wave -noupdate /tb_fpnew/count_applied
add wave -noupdate /tb_fpnew/count_checked
add wave -noupdate /tb_fpnew/fail_count
add wave -noupdate /tb_fpnew/expected_result
add wave -noupdate /tb_fpnew/sum_prod
add wave -noupdate /tb_fpnew/shifted_acc
add wave -noupdate /tb_fpnew/sum_prod_acc
add wave -noupdate /tb_fpnew/tb_sum_shifted
add wave -noupdate /tb_fpnew/shift_acc
add wave -noupdate /tb_fpnew/tb_final_exponent
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {54015 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {105 ns}
